const ActionType = {
  MACHINE_CONNECT: 'MACHINE_CONNECT',
  MACHINE_ACCEPTED: 'MACHINE_ACCEPTED',
  MACHINE_REJECTED: 'MACHINE_REJECTED',
  CONTROLLER_CONNECT: 'CONTROLLER_CONNECT',
  CONTROLLER_ACCEPTED: 'CONTROLLER_ACCEPTED',
  CONTROLLER_REJECTED: 'CONTROLLER_REJECTED',
  MACHINE_OFFLINE: 'MACHINE_OFFLINE',
  MACHINE_ONLINE: 'MACHINE_ONLINE',
  MACHINE_START: 'MACHINE_START',
  MACHINE_STARTED: 'MACHINE_STARTED',
  MACHINE_STOP: 'MACHINE_STOP',
  MACHINE_STOPPED: 'MACHINE_STOPPED',
};

module.exports = ActionType;
