const ActionType = {
  MACHINE_CONNECT: 'MACHINE_CONNECT',
  MACHINE_ACCEPTED: 'MACHINE_ACCEPTED',
  MACHINE_REJECTED: 'MACHINE_REJECTED',
  CONTROLLER_CONNECT: 'CONTROLLER_CONNECT',
  CONTROLLER_ACCEPTED: 'CONTROLLER_ACCEPTED',
  CONTROLLER_REJECTED: 'CONTROLLER_REJECTED',
  MACHINE_OFFLINE: 'MACHINE_OFFLINE',
  MACHINE_ONLINE: 'MACHINE_ONLINE',
};

module.exports = ActionType;
